=== Dualvic/Java/JavaSchemas_JAXB/src/org/foobarspam/schemas/cotxox.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="https://api.mobipalma.mobi/docs/"
	xmlns:emt="https://api.mobipalma.mobi/docs/" elementFormDefault="unqualified">

	<element name="carrera" type="emt:Carrera"></element>

	<complexType name="Carrera">
		<sequence>
			<element name="conductor" type="emt:Conductor"></element>
			<element name="tarjetaCredito" type="string"></element>
			<element name="origen" type="string"></element>
			<element name="destino" type="string"></element>
			<element name="tiempoEsperadoMinutos" type="int"></element>
			<element name="distancia" type="double"></element>
			<element name="costeTotal" type="double"></element>
			<element name="propina" type="double"></element>
		</sequence>
	</complexType>

	<complexType name="Conductor">
		<sequence>
			<element name="nombre" type="string"></element>
			<element name="modeloCoche" type="string"></element>
			<element name="matricula" type="string"></element>
			<element name="valoracionMedia" type="double"></element>
			<element name="ocupado" type="boolean"></element>
			<element name="valoraciones" type="double" maxOccurs="unbounded"
				minOccurs="0"></element>
		</sequence>
	</complexType>

</schema>

=== Dualvic/Java/JavaSchemas_JAXB/build/classes/org/foobarspam/schemas/cotxox.xml
<?xml version="1.0" encoding="UTF-8"?>
<emt:carrera xmlns:emt="https://api.mobipalma.mobi/docs/"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://api.mobipalma.mobi/docs/ cotxox.xsd">
	<conductor>
		<nombre>Pepe</nombre>
		<modeloCoche>Seat</modeloCoche>
		<matricula>4432GLT</matricula>
		<valoracionMedia>3</valoracionMedia>
		<ocupado>false</ocupado>
		<valoraciones>7</valoraciones>
	</conductor>
	<tarjetaCredito>Visa, 23421345234567239</tarjetaCredito>
	<origen>Palma</origen>
	<destino>Soller</destino>
	<tiempoEsperadoMinutos>23</tiempoEsperadoMinutos>
	<distancia>23.2</distancia>
	<costeTotal>50</costeTotal>
	<propina>7</propina>


</emt:carrera>
